[2025-03-27T18:26:08.884+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T18:26:08.920+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.set_stage scheduled__2025-03-27T18:20:00+00:00 [queued]>
[2025-03-27T18:26:08.937+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.set_stage scheduled__2025-03-27T18:20:00+00:00 [queued]>
[2025-03-27T18:26:08.938+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 1
[2025-03-27T18:26:08.960+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): set_stage> on 2025-03-27 18:20:00+00:00
[2025-03-27T18:26:08.974+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-27T18:26:08.976+0000] {standard_task_runner.py:72} INFO - Started process 219 to run task
[2025-03-27T18:26:08.975+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'set_stage', 'scheduled__2025-03-27T18:20:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/HW6_ETL.py', '--cfg-path', '/tmp/tmpa2yvspdx']
[2025-03-27T18:26:08.981+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask set_stage
[2025-03-27T18:26:09.068+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL.set_stage scheduled__2025-03-27T18:20:00+00:00 [running]> on host 67dc0bf42bd4
[2025-03-27T18:26:09.240+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='set_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T18:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T18:20:00+00:00'
[2025-03-27T18:26:09.243+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T18:26:09.271+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-27T18:26:09.274+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-27T18:26:09.276+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-27T18:26:09.278+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-27T18:26:09.653+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:26:09.790+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:26:09.885+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:26:10.041+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:26:10.191+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:26:10.192+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T18:26:10.206+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T18:26:10.207+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=set_stage, run_id=scheduled__2025-03-27T18:20:00+00:00, execution_date=20250327T182000, start_date=20250327T182608, end_date=20250327T182610
[2025-03-27T18:26:10.257+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T18:26:10.282+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T18:26:10.286+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
